### ISSUE TITLE
Misuse of the ASF's Kafka trademark in KafkaCenter

### ISSUE THREAD

**Issue by junrao** [xaecbd/KCenter#123]
Hi,

On behalf of the Apache Kafka PMC, I am emailing you about KafkaCenter (https://github.com/xaecbd/KafkaCenter).

You may not be aware of this, but the name KafkaCenter actually misuses the Apache Kafka trademark. For details, please see https://www.apache.org/foundation/marks/faq/#poweredby. In general, the name in the form of  "foo for Apache Kafka" or "foo powered by Apache Kafka" would both be acceptable.

We'd appreciate it if you can fix the misuse accordingly.

Thank you for your time and respect for the Apache trademark.

Jun Rao
on behalf of the Apache Kafka PMC

**Comment by TrumanDu** [comment]
[In progress](https://github.com/xaecbd/KafkaCenter/projects/1#card-73394163)

**Comment by TrumanDu** [comment]
Due to COVID-19， the release was postponed to 2022-1-31.

**Comment by TrumanDu** [comment]
the release was postponed to 2022-2-28.

**Comment by TrumanDu** [comment]
done

**Comment by junrao** [comment]
Thank you, @TrumanDu !
